DEVICE: "cuda"
SEED_VALUE: 4321
LOGDIR: ""
EXP_NAME: "v5_h36m_fcn_N5_10_oml0.01acc"
DEBUG: True
OUTPUT_DIR: "results"

DATASET_NAME: "h36m"
ESTIMATOR: "fcn"
BODY_REPRESENTATION: "3D"
GPUS: ["2"]
SAMPLE_INTERVAL: 5

SMPL_MODEL_DIR: "data/smpl/"

# CUDNN config
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

# model config
MODEL:
  TYPE: "network"
  NAME: ""
  # sampling setting
  SAMPLE_TYPE: "uniform"
  SLIDE_WINDOW_Q: 20
  DROPOUT: 0.1

  ENCODER_RESIDUAL: True
  ENCODER_HEAD: 4
  ENCODER_TRANSFORMER_BLOCK: 5
  ENCODER_EMBEDDING_DIMENSION: 64

  DECODER: "transformer"
  DECODER_INTERP: "linear"
  DECODER_RESIDUAL: True
  DECODER_HEAD: 4
  DECODER_TRANSFORMER_BLOCK: 5
  DECODER_EMBEDDING_DIMENSION: 64
  DECODER_TOKEN_WINDOW: 5

# training config
TRAIN:
  BATCH_SIZE: 96
  WORKERS_NUM: 0
  EPOCH: 100
  LR: 0.001
  LRDECAY: 0.95
  RESUME: None
  VALIDATE: True
  USE_SMPL_LOSS: False
  USE_6D_SMPL: False
  PRE_NORM: True

# test config
EVALUATE:
  PRETRAINED: "results/29-08-2022_08-31-47_h36m_fcn_N5_10/checkpoint.pth.tar"
  PRETRAINED_DECI: "data/checkpoints/h36m_fcn_3D/checkpoint.pth.tar"
  ROOT_RELATIVE: True
  SLIDE_WINDOW_STEP_Q: 1
  INTERP: "linear"
  RELATIVE_IMPROVEMENT: False
  DENOISE: False

# loss config
LOSS:
  LAMADA: 1.0
  W_DENOISE: 1.0

VIS:
  INPUT_VIDEO_NUMBER: 143
  INPUT_VIDEO_PATH: "data/videos/"
  OUTPUT_VIDEO_PATH: "demo/"
  START: 750
  END: 1250
