DEVICE: "cuda"
SEED_VALUE: 4321
LOGDIR: ""
EXP_NAME: "B256_aist_spin_3D_N5_10_l5_c32"
DEBUG: True
OUTPUT_DIR: "results"

DATASET_NAME: "aist"
ESTIMATOR: "spin"
BODY_REPRESENTATION: "3D"
SAMPLE_INTERVAL: 5
GPUS: ["0", "1"]

SMPL_MODEL_DIR: "data/smpl/"

# CUDNN config
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

# model config
MODEL:
  TYPE: "network"
  NAME: ""
  # sampling setting
  SAMPLE_TYPE: "uniform"
  SLIDE_WINDOW_Q: 20
  DROPOUT: 0.1

  ENCODER_RESIDUAL: True
  ENCODER_HEAD: 4
  ENCODER_TRANSFORMER_BLOCK: 5
  ENCODER_EMBEDDING_DIMENSION: 32

  DECODER: "transformer"
  DECODER_INTERP: "linear"
  DECODER_RESIDUAL: True
  DECODER_HEAD: 4
  DECODER_TRANSFORMER_BLOCK: 5
  DECODER_EMBEDDING_DIMENSION: 32
  DECODER_TOKEN_WINDOW: 5

# training config
TRAIN:
  BATCH_SIZE: 256
  WORKERS_NUM: 0
  EPOCH: 100
  LR: 0.001
  LRDECAY: 0.95
  RESUME: "./results/03-02-2023_11-30-03_B256_aist_spin_3D_N5_10_l5_c32/EP7_mpjpe_66.3150_checkpoint.pth.tar"
  VALIDATE: True
  USE_SMPL_LOSS: False
  USE_6D_SMPL: False
  PRE_NORM: True

# test config
EVALUATE:
  PRETRAINED: "results/27-02-2023_02-36-57_B256_aist_spin_3D_N5_10_l5_c32/EP11_mpjpe_65.4849_checkpoint.pth.tar"
  # PRETRAINED: "results/29-08-2022_18-00-27_aist_spin_3D_N5_10/checkpoint.pth.tar"
  PRETRAINED_DECI: "data/checkpoints/aist_spin_3D/checkpoint.pth.tar"
  ROOT_RELATIVE: True
  SLIDE_WINDOW_STEP_Q: 1
  INTERP: "linear"
  RELATIVE_IMPROVEMENT: False
  DENOISE: False

# loss config
LOSS:
  LAMADA: 5.0
  W_DENOISE: 1.0

VIS:
  INPUT_VIDEO_NUMBER: 11
  INPUT_VIDEO_PATH: "data/videos/"
  OUTPUT_VIDEO_PATH: "demo/"
  START: 0
  END: 500
