DEVICE: "cuda"
SEED_VALUE: 4321
LOGDIR: ""
EXP_NAME: "pw3d_pare_smpl_N5_10_7enc"
DEBUG: True
OUTPUT_DIR: "results"

DATASET_NAME: "pw3d"
ESTIMATOR: "pare"
BODY_REPRESENTATION: "smpl"
SAMPLE_INTERVAL: 10
GPUS: ["1"]

SMPL_MODEL_DIR: "data/smpl/"

# CUDNN config
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

# model config
MODEL:
  TYPE: "network"
  NAME: ""
  # sampling setting
  SAMPLE_TYPE: "uniform"
  SLIDE_WINDOW_Q: 10
  DROPOUT: 0.1

  ENCODER_RESIDUAL: True
  ENCODER_HEAD: 4
  ENCODER_TRANSFORMER_BLOCK: 5
  ENCODER_EMBEDDING_DIMENSION: 128

  DECODER: "transformer"
  DECODER_INTERP: "linear"
  DECODER_RESIDUAL: True
  DECODER_HEAD: 4
  DECODER_TRANSFORMER_BLOCK: 5
  DECODER_EMBEDDING_DIMENSION: 128
  DECODER_TOKEN_WINDOW: 5

# training config
TRAIN:
  BATCH_SIZE: 128
  WORKERS_NUM: 0
  EPOCH: 70
  LR: 0.001
  LRDECAY: 0.95
  RESUME: None
  VALIDATE: True
  USE_SMPL_LOSS: False
  USE_6D_SMPL: True
  PRE_NORM: False

# test config
EVALUATE:
  PRETRAINED: "results/17-08-2022_21-03-49_pw3d_pare/checkpoint.pth.tar"
  ROOT_RELATIVE: True
  SLIDE_WINDOW_STEP_Q: 1
  INTERP: "linear"
  RELATIVE_IMPROVEMENT: False
  DENOISE: False

# loss config
LOSS:
  LAMADA: 5.0
  W_DENOISE: 1.0

VIS:
  INPUT_VIDEO_NUMBER: 18
  INPUT_VIDEO_PATH: "data/videos/"
  OUTPUT_VIDEO_PATH: "demo/"
  START: 0
  END: 1000
